title: Samuel Martinelli
email: skmartinelli@gmail.com
baseurl: ""
url: "https://sammartinelli.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed


